# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - swerve_arm_controller

  swerve_arm_controller:
    type: FollowJointTrajectory
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J_END_EFF